### ISSUE TITLE
Vulnerabilities Incorrect / Links Wrong

### ISSUE THREAD

**Issue by olivov** [container-registry/backstage-plugin-harbor#239]
We're currently running the latest Harbor version, 2.8.0 and having a couple issues trying to get this plugin working in our backstage instance:

1. The vulnerabilities listed always shows **None** (The vulnerabilities for each of these images should be at least **High** or **Critical**)
<img width="1349" alt="Screenshot 2023-08-01 at 9 22 38 PM" src="https://github.com/container-registry/backstage-plugin-harbor/assets/23345433/bd448ec2-664b-43e7-aa3e-76316d8cf35e">

2. The **LEARN MORE** link is incorrect
The current link to the artifact in the UI seems to be structured as follows:
`[baseUrl]/harbor/projects/[projectNumber]/repositories/[repoName]/artifacts/[firstArtifactTag]`
The link structure for the latest Harbor release should be:
`[baseUrl]/harbor/projects/[projectNumber]/repositories/[repoName]/artifacts-tab/artifacts/[fullArtifactSha]`

Has anyone else had success with the above in a newer version of Harbor?

**Comment by kamroy** [comment]
Hi @olivov,  did you find any solution or workaround for this issue?

**Comment by pierrevillard** [comment]
Hi @olivov @kamroy 

Same here !

**Comment by Vad1mo** [comment]
Can someone take a look, happy to accept the PRs

**Comment by locomoco28** [comment]
I am looking into this. I fixed the link, but I couldn't understand how the proxying stuff works. I've also been quite busy today tho.

**Comment by locomoco28** [comment]
I think it's the old API that doesn't work. Using API v2 

https://github.com/container-registry/backstage-plugin-harbor/blob/982d6e58bb2469241f903aac8737ef489f9f5685/src/components/HarborRepository/HarborRepository.tsx#L19

Needs to be

```js
    const response = await fetchApi.fetch(
      `${backendUrl}/api/v2.0/projects/${props.project}/repositories/${props.repository}?with_tag=false&with_scan_overview=true&with_label=false&with_accessory=false`
    )
  ```
  
  The response keys probably change too. I'd like to implement this, but I don't know how I can load a modified version of this plugin in Backstage. I tried just cloning the repo in the `plugins` folder in the project root, but I dunno how I can replace the NPM package with my local clone. Can someone give me a hint?

**Comment by kamroy** [comment]
@locomoco28  you should look backstage-plugin-harbor-backend  to see the real api call.

**Comment by locomoco28** [comment]
> @locomoco28 you should look backstage-plugin-harbor-backend to see the real api call.

Oh my bad lmao  
That makes a lot more sense

---

https://github.com/container-registry/backstage-plugin-harbor-backend/blob/38600a4cf2d3b062d2aab9ecc7bfa1fe1a230026/src/service/artifact.ts#L45C24-L46

`application/vnd.security.vulnerability.report; version=1.1` is my key for vulns. That key seems to change.

Instead of fetching the vulns by their reference href, the `sett` param could be set to true to get them included in the first fetch though

https://github.com/container-registry/backstage-plugin-harbor-backend/blob/38600a4cf2d3b062d2aab9ecc7bfa1fe1a230026/src/service/artifact.ts#L17

There is no detailed breakdown on vulns anyways so...

Thanks for the hint kamroy :)

**Comment by locomoco28** [comment]
I still have the problem that I don't know how to test this though...

https://github.com/container-registry/backstage-plugin-harbor-backend/pull/110
