### ISSUE TITLE
Learn More Button 404

### ISSUE THREAD

**Issue by billabongrob** [container-registry/backstage-plugin-harbor#271]
The `Learn More` button on the Harbor plugin goes to a 404
![Screenshot 2024-03-13 at 9 30 57 AM](https://github.com/container-registry/backstage-plugin-harbor/assets/8441943/6d593853-dfa9-47f6-8c1a-5a70d87591d8)

Example URL is:  https://TLD/harbor/projects/5/repositories/<name>/artifacts/<slug>

**Comment by psmietanaa** [comment]
What Harbor version are you using @billabongrob?

According to latest Harbor version (2.9.4), it should be `https://TLD/harbor/projects/100/repositories/bitnami%2Fpostgresql/artifacts-tab/artifacts/12-debian-9`

**Comment by billabongrob** [comment]
This does appear to be working in our production environment.  Apologies for the confusion - we've reverted to an older version of the plugin.
